#!/bin/bash
set -eu
### -*- mode: conf-unix; -*-

##################################################

ProgramName=skeletor-haskell

echo ----------------------------------------
echo
echo "${ProgramName}"
echo

echo ----------------------------------------
echo

command -v cabal

echo
echo ----------------------------------------
echo

echo ----------------------------------------
echo

cabal new-build "skeletor:exe:${ProgramName}"

echo
echo ----------------------------------------

ProgramPath=$(cabal new-exec -- which "${ProgramName}")

echo
echo "${ProgramPath}"
echo
echo ----------------------------------------
echo

touch "${ProgramName}"
ln -sf "${ProgramPath}" "./${ProgramName}"

echo ----------------------------------------
echo

"${ProgramPath}" --bash-completion-script "${ProgramPath}"

echo
echo ----------------------------------------
